backend:
  name: git-gateway
  branch: main

media_folder: blog/images
public_folder: /blog/images

collections:
  - name: posts
    label: Blog Posts
    label_singular: Blog Post
    folder: blog/posts
    create: true
    slug: "{{slug}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Publish Date, name: date, widget: datetime, format: "YYYY-MM-DD", date_format: "DD/MM/YYYY", time_format: false }
      - { label: "Short Summary (shown in Google)", name: excerpt, widget: text, hint: "1-2 sentences. This is what people see in search results." }
      - { label: Body, name: body, widget: markdown }
